### ISSUE TITLE
Update Package Incorrect v2.0.2.0

### ISSUE THREAD

**Issue by kynrek** [MiSTer-devel/SD-InstallTool_Win_MiSTer#2]
When I run the application it says Update Package Incorrect v2.0.2.0. I just downloaded the application and windows said I needed the .net framework so I installed it. Not sure if there is another setup step that I am missing. 

 I have added the log messages below:
CheckUpdatePackage()...
done
Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
Object reference not set to an instance of an object.
CheckPartialUpdateCompatible()...
Reading MBR from disk \\.\PHYSICALDRIVE10
Read successful 512 bytes
ErrorCode: 0x80004005, Message: 'Access is denied'
Card is incompatible with MiSTer
At least 2 partitions required. Found only 0
Use 'Full Install' option to repartition
done

**Comment by sorgelig** [comment]
Which Windows version do you use?

**Comment by kynrek** [comment]
I was using winows 10. I just realized that I only downloaded the sd install tool program itself (without any of the other mister project files). Once I downloaded the whole project it worked fine. Sorry for the confusion.

**Comment by hawkeye73** [comment]
I have the same issue. Maybe on the notes with requirements state the files have to be in which location. Now it seems like you download the tool and that is all you need.
